// app/layout.tsx
import "./globals.css";
import React from "react";
import NavigationBar from "./components/nav";

export const metadata = {
  title: "Suscon - Sustainable Construction",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="no">
      <body className="bg-gray-200 text-black">
        <div className="grid min-h-screen grid-rows-[auto_1fr_auto] max-w-screen-xl mx-auto">
          <NavigationBar />
          <main>{children}</main>
          <footer className="bg-gray-100 text-center py-4">Footer</footer>
        </div>
      </body>
    </html>
  );
}
